#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace innosoft_crm.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="innosoft_crm")]
	public partial class innosoft_crmDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertinnosoft_mstActionType(innosoft_mstActionType instance);
    partial void Updateinnosoft_mstActionType(innosoft_mstActionType instance);
    partial void Deleteinnosoft_mstActionType(innosoft_mstActionType instance);
    partial void Insertinnosoft_trnProjectAction(innosoft_trnProjectAction instance);
    partial void Updateinnosoft_trnProjectAction(innosoft_trnProjectAction instance);
    partial void Deleteinnosoft_trnProjectAction(innosoft_trnProjectAction instance);
    partial void Insertinnosoft_mstCallStatus(innosoft_mstCallStatus instance);
    partial void Updateinnosoft_mstCallStatus(innosoft_mstCallStatus instance);
    partial void Deleteinnosoft_mstCallStatus(innosoft_mstCallStatus instance);
    partial void Insertinnosoft_mstCustomer(innosoft_mstCustomer instance);
    partial void Updateinnosoft_mstCustomer(innosoft_mstCustomer instance);
    partial void Deleteinnosoft_mstCustomer(innosoft_mstCustomer instance);
    partial void Insertinnosoft_mstProduct(innosoft_mstProduct instance);
    partial void Updateinnosoft_mstProduct(innosoft_mstProduct instance);
    partial void Deleteinnosoft_mstProduct(innosoft_mstProduct instance);
    partial void Insertinnosoft_mstProjectStatus(innosoft_mstProjectStatus instance);
    partial void Updateinnosoft_mstProjectStatus(innosoft_mstProjectStatus instance);
    partial void Deleteinnosoft_mstProjectStatus(innosoft_mstProjectStatus instance);
    partial void Insertinnosoft_mstStaff(innosoft_mstStaff instance);
    partial void Updateinnosoft_mstStaff(innosoft_mstStaff instance);
    partial void Deleteinnosoft_mstStaff(innosoft_mstStaff instance);
    partial void Insertinnosoft_trnCall(innosoft_trnCall instance);
    partial void Updateinnosoft_trnCall(innosoft_trnCall instance);
    partial void Deleteinnosoft_trnCall(innosoft_trnCall instance);
    partial void Insertinnosoft_trnCallAction(innosoft_trnCallAction instance);
    partial void Updateinnosoft_trnCallAction(innosoft_trnCallAction instance);
    partial void Deleteinnosoft_trnCallAction(innosoft_trnCallAction instance);
    partial void Insertinnosoft_trnProject(innosoft_trnProject instance);
    partial void Updateinnosoft_trnProject(innosoft_trnProject instance);
    partial void Deleteinnosoft_trnProject(innosoft_trnProject instance);
    #endregion
		
		public innosoft_crmDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["innosoft_crmConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public innosoft_crmDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public innosoft_crmDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public innosoft_crmDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public innosoft_crmDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<innosoft_mstActionType> innosoft_mstActionTypes
		{
			get
			{
				return this.GetTable<innosoft_mstActionType>();
			}
		}
		
		public System.Data.Linq.Table<innosoft_trnProjectAction> innosoft_trnProjectActions
		{
			get
			{
				return this.GetTable<innosoft_trnProjectAction>();
			}
		}
		
		public System.Data.Linq.Table<innosoft_mstCallStatus> innosoft_mstCallStatus
		{
			get
			{
				return this.GetTable<innosoft_mstCallStatus>();
			}
		}
		
		public System.Data.Linq.Table<innosoft_mstCustomer> innosoft_mstCustomers
		{
			get
			{
				return this.GetTable<innosoft_mstCustomer>();
			}
		}
		
		public System.Data.Linq.Table<innosoft_mstProduct> innosoft_mstProducts
		{
			get
			{
				return this.GetTable<innosoft_mstProduct>();
			}
		}
		
		public System.Data.Linq.Table<innosoft_mstProjectStatus> innosoft_mstProjectStatus
		{
			get
			{
				return this.GetTable<innosoft_mstProjectStatus>();
			}
		}
		
		public System.Data.Linq.Table<innosoft_mstStaff> innosoft_mstStaffs
		{
			get
			{
				return this.GetTable<innosoft_mstStaff>();
			}
		}
		
		public System.Data.Linq.Table<innosoft_trnCall> innosoft_trnCalls
		{
			get
			{
				return this.GetTable<innosoft_trnCall>();
			}
		}
		
		public System.Data.Linq.Table<innosoft_trnCallAction> innosoft_trnCallActions
		{
			get
			{
				return this.GetTable<innosoft_trnCallAction>();
			}
		}
		
		public System.Data.Linq.Table<innosoft_trnProject> innosoft_trnProjects
		{
			get
			{
				return this.GetTable<innosoft_trnProject>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.innosoft_mstActionType")]
	public partial class innosoft_mstActionType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ActionType;
		
		private System.Data.Linq.Binary _ActionImage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnActionTypeChanging(string value);
    partial void OnActionTypeChanged();
    partial void OnActionImageChanging(System.Data.Linq.Binary value);
    partial void OnActionImageChanged();
    #endregion
		
		public innosoft_mstActionType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionType", DbType="NVarChar(50)")]
		public string ActionType
		{
			get
			{
				return this._ActionType;
			}
			set
			{
				if ((this._ActionType != value))
				{
					this.OnActionTypeChanging(value);
					this.SendPropertyChanging();
					this._ActionType = value;
					this.SendPropertyChanged("ActionType");
					this.OnActionTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ActionImage
		{
			get
			{
				return this._ActionImage;
			}
			set
			{
				if ((this._ActionImage != value))
				{
					this.OnActionImageChanging(value);
					this.SendPropertyChanging();
					this._ActionImage = value;
					this.SendPropertyChanged("ActionImage");
					this.OnActionImageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.innosoft_trnProjectAction")]
	public partial class innosoft_trnProjectAction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _ProjectId;
		
		private System.Nullable<int> _Programmer;
		
		private string _Issue;
		
		private string _Action;
		
		private System.Nullable<System.DateTime> _EncodedDateTime;
		
		private System.Nullable<System.DateTime> _StartedDateTime;
		
		private System.Nullable<System.DateTime> _EndDateTime;
		
		private System.Nullable<decimal> _NumberOfHours;
		
		private System.Nullable<bool> _Done;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnProjectIdChanging(System.Nullable<int> value);
    partial void OnProjectIdChanged();
    partial void OnProgrammerChanging(System.Nullable<int> value);
    partial void OnProgrammerChanged();
    partial void OnIssueChanging(string value);
    partial void OnIssueChanged();
    partial void OnActionChanging(string value);
    partial void OnActionChanged();
    partial void OnEncodedDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnEncodedDateTimeChanged();
    partial void OnStartedDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnStartedDateTimeChanged();
    partial void OnEndDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDateTimeChanged();
    partial void OnNumberOfHoursChanging(System.Nullable<decimal> value);
    partial void OnNumberOfHoursChanged();
    partial void OnDoneChanging(System.Nullable<bool> value);
    partial void OnDoneChanged();
    #endregion
		
		public innosoft_trnProjectAction()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectId", DbType="Int")]
		public System.Nullable<int> ProjectId
		{
			get
			{
				return this._ProjectId;
			}
			set
			{
				if ((this._ProjectId != value))
				{
					this.OnProjectIdChanging(value);
					this.SendPropertyChanging();
					this._ProjectId = value;
					this.SendPropertyChanged("ProjectId");
					this.OnProjectIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Programmer", DbType="Int")]
		public System.Nullable<int> Programmer
		{
			get
			{
				return this._Programmer;
			}
			set
			{
				if ((this._Programmer != value))
				{
					this.OnProgrammerChanging(value);
					this.SendPropertyChanging();
					this._Programmer = value;
					this.SendPropertyChanged("Programmer");
					this.OnProgrammerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Issue", DbType="NVarChar(255)")]
		public string Issue
		{
			get
			{
				return this._Issue;
			}
			set
			{
				if ((this._Issue != value))
				{
					this.OnIssueChanging(value);
					this.SendPropertyChanging();
					this._Issue = value;
					this.SendPropertyChanged("Issue");
					this.OnIssueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Action", DbType="NVarChar(255)")]
		public string Action
		{
			get
			{
				return this._Action;
			}
			set
			{
				if ((this._Action != value))
				{
					this.OnActionChanging(value);
					this.SendPropertyChanging();
					this._Action = value;
					this.SendPropertyChanged("Action");
					this.OnActionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EncodedDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> EncodedDateTime
		{
			get
			{
				return this._EncodedDateTime;
			}
			set
			{
				if ((this._EncodedDateTime != value))
				{
					this.OnEncodedDateTimeChanging(value);
					this.SendPropertyChanging();
					this._EncodedDateTime = value;
					this.SendPropertyChanged("EncodedDateTime");
					this.OnEncodedDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartedDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartedDateTime
		{
			get
			{
				return this._StartedDateTime;
			}
			set
			{
				if ((this._StartedDateTime != value))
				{
					this.OnStartedDateTimeChanging(value);
					this.SendPropertyChanging();
					this._StartedDateTime = value;
					this.SendPropertyChanged("StartedDateTime");
					this.OnStartedDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDateTime
		{
			get
			{
				return this._EndDateTime;
			}
			set
			{
				if ((this._EndDateTime != value))
				{
					this.OnEndDateTimeChanging(value);
					this.SendPropertyChanging();
					this._EndDateTime = value;
					this.SendPropertyChanged("EndDateTime");
					this.OnEndDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOfHours", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> NumberOfHours
		{
			get
			{
				return this._NumberOfHours;
			}
			set
			{
				if ((this._NumberOfHours != value))
				{
					this.OnNumberOfHoursChanging(value);
					this.SendPropertyChanging();
					this._NumberOfHours = value;
					this.SendPropertyChanged("NumberOfHours");
					this.OnNumberOfHoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Done", DbType="Bit")]
		public System.Nullable<bool> Done
		{
			get
			{
				return this._Done;
			}
			set
			{
				if ((this._Done != value))
				{
					this.OnDoneChanging(value);
					this.SendPropertyChanging();
					this._Done = value;
					this.SendPropertyChanged("Done");
					this.OnDoneChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.innosoft_mstCallStatus")]
	public partial class innosoft_mstCallStatus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _CallStatus;
		
		private System.Data.Linq.Binary _StatusImage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCallStatusChanging(string value);
    partial void OnCallStatusChanged();
    partial void OnStatusImageChanging(System.Data.Linq.Binary value);
    partial void OnStatusImageChanged();
    #endregion
		
		public innosoft_mstCallStatus()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallStatus", DbType="NVarChar(50)")]
		public string CallStatus
		{
			get
			{
				return this._CallStatus;
			}
			set
			{
				if ((this._CallStatus != value))
				{
					this.OnCallStatusChanging(value);
					this.SendPropertyChanging();
					this._CallStatus = value;
					this.SendPropertyChanged("CallStatus");
					this.OnCallStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary StatusImage
		{
			get
			{
				return this._StatusImage;
			}
			set
			{
				if ((this._StatusImage != value))
				{
					this.OnStatusImageChanging(value);
					this.SendPropertyChanging();
					this._StatusImage = value;
					this.SendPropertyChanged("StatusImage");
					this.OnStatusImageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.innosoft_mstCustomer")]
	public partial class innosoft_mstCustomer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _Address;
		
		private string _ContactPerson;
		
		private string _Telephone;
		
		private string _Fax;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnContactPersonChanging(string value);
    partial void OnContactPersonChanged();
    partial void OnTelephoneChanging(string value);
    partial void OnTelephoneChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    #endregion
		
		public innosoft_mstCustomer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(255)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPerson", DbType="NVarChar(255)")]
		public string ContactPerson
		{
			get
			{
				return this._ContactPerson;
			}
			set
			{
				if ((this._ContactPerson != value))
				{
					this.OnContactPersonChanging(value);
					this.SendPropertyChanging();
					this._ContactPerson = value;
					this.SendPropertyChanged("ContactPerson");
					this.OnContactPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="NVarChar(100)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this.OnTelephoneChanging(value);
					this.SendPropertyChanging();
					this._Telephone = value;
					this.SendPropertyChanged("Telephone");
					this.OnTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(100)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.innosoft_mstProduct")]
	public partial class innosoft_mstProduct : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnProductChanging(string value);
    partial void OnProductChanged();
    #endregion
		
		public innosoft_mstProduct()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product", DbType="NVarChar(255)")]
		public string Product
		{
			get
			{
				return this._Product;
			}
			set
			{
				if ((this._Product != value))
				{
					this.OnProductChanging(value);
					this.SendPropertyChanging();
					this._Product = value;
					this.SendPropertyChanged("Product");
					this.OnProductChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.innosoft_mstProjectStatus")]
	public partial class innosoft_mstProjectStatus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ProjectStatus;
		
		private System.Data.Linq.Binary _StatusImage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnProjectStatusChanging(string value);
    partial void OnProjectStatusChanged();
    partial void OnStatusImageChanging(System.Data.Linq.Binary value);
    partial void OnStatusImageChanged();
    #endregion
		
		public innosoft_mstProjectStatus()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectStatus", DbType="NVarChar(50)")]
		public string ProjectStatus
		{
			get
			{
				return this._ProjectStatus;
			}
			set
			{
				if ((this._ProjectStatus != value))
				{
					this.OnProjectStatusChanging(value);
					this.SendPropertyChanging();
					this._ProjectStatus = value;
					this.SendPropertyChanged("ProjectStatus");
					this.OnProjectStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary StatusImage
		{
			get
			{
				return this._StatusImage;
			}
			set
			{
				if ((this._StatusImage != value))
				{
					this.OnStatusImageChanging(value);
					this.SendPropertyChanging();
					this._StatusImage = value;
					this.SendPropertyChanged("StatusImage");
					this.OnStatusImageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.innosoft_mstStaff")]
	public partial class innosoft_mstStaff : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _Address;
		
		private string _Telephone;
		
		private string _EMail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnTelephoneChanging(string value);
    partial void OnTelephoneChanged();
    partial void OnEMailChanging(string value);
    partial void OnEMailChanged();
    #endregion
		
		public innosoft_mstStaff()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(255)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="NVarChar(50)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this.OnTelephoneChanging(value);
					this.SendPropertyChanging();
					this._Telephone = value;
					this.SendPropertyChanged("Telephone");
					this.OnTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="NVarChar(50)")]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this.OnEMailChanging(value);
					this.SendPropertyChanging();
					this._EMail = value;
					this.SendPropertyChanged("EMail");
					this.OnEMailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.innosoft_trnCall")]
	public partial class innosoft_trnCall : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.DateTime> _DateCalled;
		
		private System.Nullable<int> _CustomerId;
		
		private System.Nullable<int> _ProductId;
		
		private string _Caller;
		
		private string _Issue;
		
		private System.Nullable<int> _CallStatusId;
		
		private System.Nullable<int> _AnsweredById;
		
		private System.Nullable<int> _AssignedToId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDateCalledChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCalledChanged();
    partial void OnCustomerIdChanging(System.Nullable<int> value);
    partial void OnCustomerIdChanged();
    partial void OnProductIdChanging(System.Nullable<int> value);
    partial void OnProductIdChanged();
    partial void OnCallerChanging(string value);
    partial void OnCallerChanged();
    partial void OnIssueChanging(string value);
    partial void OnIssueChanged();
    partial void OnCallStatusIdChanging(System.Nullable<int> value);
    partial void OnCallStatusIdChanged();
    partial void OnAnsweredByIdChanging(System.Nullable<int> value);
    partial void OnAnsweredByIdChanged();
    partial void OnAssignedToIdChanging(System.Nullable<int> value);
    partial void OnAssignedToIdChanged();
    #endregion
		
		public innosoft_trnCall()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCalled", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCalled
		{
			get
			{
				return this._DateCalled;
			}
			set
			{
				if ((this._DateCalled != value))
				{
					this.OnDateCalledChanging(value);
					this.SendPropertyChanging();
					this._DateCalled = value;
					this.SendPropertyChanged("DateCalled");
					this.OnDateCalledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerId", DbType="Int")]
		public System.Nullable<int> CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				if ((this._CustomerId != value))
				{
					this.OnCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._CustomerId = value;
					this.SendPropertyChanged("CustomerId");
					this.OnCustomerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="Int")]
		public System.Nullable<int> ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this.OnProductIdChanging(value);
					this.SendPropertyChanging();
					this._ProductId = value;
					this.SendPropertyChanged("ProductId");
					this.OnProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caller", DbType="NVarChar(50)")]
		public string Caller
		{
			get
			{
				return this._Caller;
			}
			set
			{
				if ((this._Caller != value))
				{
					this.OnCallerChanging(value);
					this.SendPropertyChanging();
					this._Caller = value;
					this.SendPropertyChanged("Caller");
					this.OnCallerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Issue", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Issue
		{
			get
			{
				return this._Issue;
			}
			set
			{
				if ((this._Issue != value))
				{
					this.OnIssueChanging(value);
					this.SendPropertyChanging();
					this._Issue = value;
					this.SendPropertyChanged("Issue");
					this.OnIssueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallStatusId", DbType="Int")]
		public System.Nullable<int> CallStatusId
		{
			get
			{
				return this._CallStatusId;
			}
			set
			{
				if ((this._CallStatusId != value))
				{
					this.OnCallStatusIdChanging(value);
					this.SendPropertyChanging();
					this._CallStatusId = value;
					this.SendPropertyChanged("CallStatusId");
					this.OnCallStatusIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnsweredById", DbType="Int")]
		public System.Nullable<int> AnsweredById
		{
			get
			{
				return this._AnsweredById;
			}
			set
			{
				if ((this._AnsweredById != value))
				{
					this.OnAnsweredByIdChanging(value);
					this.SendPropertyChanging();
					this._AnsweredById = value;
					this.SendPropertyChanged("AnsweredById");
					this.OnAnsweredByIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssignedToId", DbType="Int")]
		public System.Nullable<int> AssignedToId
		{
			get
			{
				return this._AssignedToId;
			}
			set
			{
				if ((this._AssignedToId != value))
				{
					this.OnAssignedToIdChanging(value);
					this.SendPropertyChanging();
					this._AssignedToId = value;
					this.SendPropertyChanged("AssignedToId");
					this.OnAssignedToIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.innosoft_trnCallAction")]
	public partial class innosoft_trnCallAction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _CallId;
		
		private System.Nullable<int> _ActedBy;
		
		private string _Action;
		
		private System.Nullable<System.DateTime> _EncodedDate;
		
		private System.Nullable<System.DateTime> _TargetDate;
		
		private System.Nullable<System.DateTime> _AcceptedDate;
		
		private string _AcceptedBy;
		
		private System.Nullable<int> _ActionTypeId;
		
		private System.Nullable<decimal> _Cost;
		
		private System.Nullable<decimal> _NumberOfHours;
		
		private System.Nullable<bool> _Done;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCallIdChanging(System.Nullable<int> value);
    partial void OnCallIdChanged();
    partial void OnActedByChanging(System.Nullable<int> value);
    partial void OnActedByChanged();
    partial void OnActionChanging(string value);
    partial void OnActionChanged();
    partial void OnEncodedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEncodedDateChanged();
    partial void OnTargetDateChanging(System.Nullable<System.DateTime> value);
    partial void OnTargetDateChanged();
    partial void OnAcceptedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnAcceptedDateChanged();
    partial void OnAcceptedByChanging(string value);
    partial void OnAcceptedByChanged();
    partial void OnActionTypeIdChanging(System.Nullable<int> value);
    partial void OnActionTypeIdChanged();
    partial void OnCostChanging(System.Nullable<decimal> value);
    partial void OnCostChanged();
    partial void OnNumberOfHoursChanging(System.Nullable<decimal> value);
    partial void OnNumberOfHoursChanged();
    partial void OnDoneChanging(System.Nullable<bool> value);
    partial void OnDoneChanged();
    #endregion
		
		public innosoft_trnCallAction()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallId", DbType="Int")]
		public System.Nullable<int> CallId
		{
			get
			{
				return this._CallId;
			}
			set
			{
				if ((this._CallId != value))
				{
					this.OnCallIdChanging(value);
					this.SendPropertyChanging();
					this._CallId = value;
					this.SendPropertyChanged("CallId");
					this.OnCallIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActedBy", DbType="Int")]
		public System.Nullable<int> ActedBy
		{
			get
			{
				return this._ActedBy;
			}
			set
			{
				if ((this._ActedBy != value))
				{
					this.OnActedByChanging(value);
					this.SendPropertyChanging();
					this._ActedBy = value;
					this.SendPropertyChanged("ActedBy");
					this.OnActedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Action", DbType="NVarChar(255)")]
		public string Action
		{
			get
			{
				return this._Action;
			}
			set
			{
				if ((this._Action != value))
				{
					this.OnActionChanging(value);
					this.SendPropertyChanging();
					this._Action = value;
					this.SendPropertyChanged("Action");
					this.OnActionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EncodedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EncodedDate
		{
			get
			{
				return this._EncodedDate;
			}
			set
			{
				if ((this._EncodedDate != value))
				{
					this.OnEncodedDateChanging(value);
					this.SendPropertyChanging();
					this._EncodedDate = value;
					this.SendPropertyChanged("EncodedDate");
					this.OnEncodedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> TargetDate
		{
			get
			{
				return this._TargetDate;
			}
			set
			{
				if ((this._TargetDate != value))
				{
					this.OnTargetDateChanging(value);
					this.SendPropertyChanging();
					this._TargetDate = value;
					this.SendPropertyChanged("TargetDate");
					this.OnTargetDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcceptedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> AcceptedDate
		{
			get
			{
				return this._AcceptedDate;
			}
			set
			{
				if ((this._AcceptedDate != value))
				{
					this.OnAcceptedDateChanging(value);
					this.SendPropertyChanging();
					this._AcceptedDate = value;
					this.SendPropertyChanged("AcceptedDate");
					this.OnAcceptedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcceptedBy", DbType="NVarChar(50)")]
		public string AcceptedBy
		{
			get
			{
				return this._AcceptedBy;
			}
			set
			{
				if ((this._AcceptedBy != value))
				{
					this.OnAcceptedByChanging(value);
					this.SendPropertyChanging();
					this._AcceptedBy = value;
					this.SendPropertyChanged("AcceptedBy");
					this.OnAcceptedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionTypeId", DbType="Int")]
		public System.Nullable<int> ActionTypeId
		{
			get
			{
				return this._ActionTypeId;
			}
			set
			{
				if ((this._ActionTypeId != value))
				{
					this.OnActionTypeIdChanging(value);
					this.SendPropertyChanging();
					this._ActionTypeId = value;
					this.SendPropertyChanged("ActionTypeId");
					this.OnActionTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="Money")]
		public System.Nullable<decimal> Cost
		{
			get
			{
				return this._Cost;
			}
			set
			{
				if ((this._Cost != value))
				{
					this.OnCostChanging(value);
					this.SendPropertyChanging();
					this._Cost = value;
					this.SendPropertyChanged("Cost");
					this.OnCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOfHours", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> NumberOfHours
		{
			get
			{
				return this._NumberOfHours;
			}
			set
			{
				if ((this._NumberOfHours != value))
				{
					this.OnNumberOfHoursChanging(value);
					this.SendPropertyChanging();
					this._NumberOfHours = value;
					this.SendPropertyChanged("NumberOfHours");
					this.OnNumberOfHoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Done", DbType="Bit")]
		public System.Nullable<bool> Done
		{
			get
			{
				return this._Done;
			}
			set
			{
				if ((this._Done != value))
				{
					this.OnDoneChanging(value);
					this.SendPropertyChanging();
					this._Done = value;
					this.SendPropertyChanged("Done");
					this.OnDoneChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.innosoft_trnProject")]
	public partial class innosoft_trnProject : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.DateTime> _ProjectDate;
		
		private System.Nullable<int> _CustomerId;
		
		private System.Nullable<int> _ProductId;
		
		private System.Nullable<int> _Programmer;
		
		private string _Particulars;
		
		private System.Nullable<System.DateTime> _AcceptanceDate;
		
		private System.Nullable<int> _ProjectStatusId;
		
		private System.Nullable<int> _AccountExecutive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnProjectDateChanging(System.Nullable<System.DateTime> value);
    partial void OnProjectDateChanged();
    partial void OnCustomerIdChanging(System.Nullable<int> value);
    partial void OnCustomerIdChanged();
    partial void OnProductIdChanging(System.Nullable<int> value);
    partial void OnProductIdChanged();
    partial void OnProgrammerChanging(System.Nullable<int> value);
    partial void OnProgrammerChanged();
    partial void OnParticularsChanging(string value);
    partial void OnParticularsChanged();
    partial void OnAcceptanceDateChanging(System.Nullable<System.DateTime> value);
    partial void OnAcceptanceDateChanged();
    partial void OnProjectStatusIdChanging(System.Nullable<int> value);
    partial void OnProjectStatusIdChanged();
    partial void OnAccountExecutiveChanging(System.Nullable<int> value);
    partial void OnAccountExecutiveChanged();
    #endregion
		
		public innosoft_trnProject()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ProjectDate
		{
			get
			{
				return this._ProjectDate;
			}
			set
			{
				if ((this._ProjectDate != value))
				{
					this.OnProjectDateChanging(value);
					this.SendPropertyChanging();
					this._ProjectDate = value;
					this.SendPropertyChanged("ProjectDate");
					this.OnProjectDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerId", DbType="Int")]
		public System.Nullable<int> CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				if ((this._CustomerId != value))
				{
					this.OnCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._CustomerId = value;
					this.SendPropertyChanged("CustomerId");
					this.OnCustomerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="Int")]
		public System.Nullable<int> ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this.OnProductIdChanging(value);
					this.SendPropertyChanging();
					this._ProductId = value;
					this.SendPropertyChanged("ProductId");
					this.OnProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Programmer", DbType="Int")]
		public System.Nullable<int> Programmer
		{
			get
			{
				return this._Programmer;
			}
			set
			{
				if ((this._Programmer != value))
				{
					this.OnProgrammerChanging(value);
					this.SendPropertyChanging();
					this._Programmer = value;
					this.SendPropertyChanged("Programmer");
					this.OnProgrammerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Particulars", DbType="NVarChar(255)")]
		public string Particulars
		{
			get
			{
				return this._Particulars;
			}
			set
			{
				if ((this._Particulars != value))
				{
					this.OnParticularsChanging(value);
					this.SendPropertyChanging();
					this._Particulars = value;
					this.SendPropertyChanged("Particulars");
					this.OnParticularsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcceptanceDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> AcceptanceDate
		{
			get
			{
				return this._AcceptanceDate;
			}
			set
			{
				if ((this._AcceptanceDate != value))
				{
					this.OnAcceptanceDateChanging(value);
					this.SendPropertyChanging();
					this._AcceptanceDate = value;
					this.SendPropertyChanged("AcceptanceDate");
					this.OnAcceptanceDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectStatusId", DbType="Int")]
		public System.Nullable<int> ProjectStatusId
		{
			get
			{
				return this._ProjectStatusId;
			}
			set
			{
				if ((this._ProjectStatusId != value))
				{
					this.OnProjectStatusIdChanging(value);
					this.SendPropertyChanging();
					this._ProjectStatusId = value;
					this.SendPropertyChanged("ProjectStatusId");
					this.OnProjectStatusIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountExecutive", DbType="Int")]
		public System.Nullable<int> AccountExecutive
		{
			get
			{
				return this._AccountExecutive;
			}
			set
			{
				if ((this._AccountExecutive != value))
				{
					this.OnAccountExecutiveChanging(value);
					this.SendPropertyChanging();
					this._AccountExecutive = value;
					this.SendPropertyChanged("AccountExecutive");
					this.OnAccountExecutiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
